HOST: http://v1.api.extremmy.com

--- eXtremmy API ---

---
В случае возникновения любой ошибки ожидается application/json 
обект с полями error (идентификатор), message (сообщение для логов), 
userMessage (опциональное сообщение для пользователя).
---

-- 
Sports
Виды спорта
--
Список видов спорта
GET /sports/list
> Accept: application/json
< 200
<Content-Type: application/json
[    
    {
        "ID": 1,
        "name": "Snowboarding / Ski",
        "alias": "snowboarding"
    }
]

--
Spots
--
Список спотов
GET /spots/list{?limit,offset}
> Accept: application/json
< 200
< Contetnt-Type: application/json
[    
    {
        "ID": 1,
        "name": "Orient Jumping",
        "coordinate": [54.069073,-10.340239],
        "sports": [1,3],
        "rating": 3
    }
]


